services:
  wmh-mc-seg:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ${DATASETS_PATH}:/home/appuser/Code/datasets
    working_dir: /app
    command: bash
    ports:
      - "8765:8765"
    tty: true
    stdin_open: true
