services:
  wmh-mc-seg:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - jupyter-data:/home/appuser/.local/share/jupyter
      - ${DATASETS_PATH}:/home/appuser/Code/datasets
    working_dir: /app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
      "
    ports:
      - "8888:8888"
    tty: true
    stdin_open: true

volumes:
  jupyter-data: